sudo: required

services:
  - docker

script:
  - docker-compose run --rm appserver make test

before_deploy:
    - docker-compose run --rm appserver make ui-requirements
    - git checkout -- ui/package-lock.json
    - docker-compose run --rm appserver make dist

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: dist/upload
    repo: comet-GmbH.github.io
    target-branch: lora-app-server
    on:
      repo: comet-GmbH/lora-app-server
      branch: pln
